package events

// All returns every registered event type.
func All() []Type {
	return []Type{
		AdminAdded,
		AdminRemoved,
		Disconnect,
		Error,
		Listening,
		Presence,
		Reconnect,
		Message,
		MessageUnsent,
		MessageReaction,
		MessageRemove,
		MessageSeen,
		MessageDelivered,
		MessagePinned,
		MessageUnpinned,
		MarkRead,
		MarkUnread,
		Typing,
		ThemeChange,
		EmojiChange,
		NicknameChange,
		ThreadNameChange,
		ThreadDelete,
		ThreadAction,
		ParticipantJoined,
		ParticipantLeft,
		FriendRequestChange,
		FriendRequestListUpdate,
		PokeNotification,
		PageNotification,
		MessageBump,
		ThreadMute,
		ThreadMuteSettings,
		ThreadFolderMove,
		ThreadApprovalMode,
		ThreadApprovalQueue,
		ThreadMagicWords,
		ThreadMessageSharing,
		ThreadGameChange,
		ThreadJoinableLinkReset,
		ThreadJoinableModeChange,
		ViewerStatusChange,
		Notification,
	}
}